name = "quota-watcher"
main = "worker.ts"
compatibility_date = "2026-05-24"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "quota_db"
database_id = "526b46dd-aec4-4275-95dc-4c120c28ace0"
migrations_dir = "migrations"
